image: node:17-bullseye

stages:
  - check
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - ANAGOLAY_WEBSITE_CID

# include this where you need it. like in before_script
.install-ipfs-and-setup: &install-ipfs-and-setup |-
  echo "Downloading anagolay ipfs CLI which works with the ipfsAuthProxy."
  curl https://ipfs.anagolay.network/ipfs/bafybeiebighwouxt3vkttuhfcwb3dgr7vzxpujlqfzvngt7omnrizjajfy > /usr/local/bin/ipfsCli
  chmod +x /usr/local/bin/ipfsCli

# https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#yaml-anchors-for-scripts
.install-pnpm: &install-pnpm
  - |
    curl https://ipfs.anagolay.network/ipfs/QmeCUX9cK4YKdTbNVq3jg5cJPvz8uQiQmb4AKKd7niy4kY > /usr/local/bin/pnpm
    chmod +x /usr/local/bin/pnpm
    node --version
    pnpm --version
    git --version

is-it-pretty:
  stage: check
  before_script:
    - curl https://ipfs.anagolay.network/ipfs/QmeCUX9cK4YKdTbNVq3jg5cJPvz8uQiQmb4AKKd7niy4kY > /usr/local/bin/pnpm
    - chmod +x /usr/local/bin/pnpm
  script:
    - pnpm install
    - pnpm lint

upload-to-ipfs:
  needs: ['is-it-pretty']
  stage: deploy
  before_script:
    - *install-ipfs-and-setup
    - *install-pnpm
  script:
    - set -e

    - echo 'Building ...'
    - pnpm build

    - echo "Uploading IPFS ..."
    - IPFS_PIN=false ipfsCli upload --onlyCid build > ANAGOLAY_WEBSITE_CID
    - echo "The Website is published with the CID:" && cat ANAGOLAY_WEBSITE_CID
    - echo "https://ipfs.anagolay.network/ipfs/$(cat ANAGOLAY_WEBSITE_CID)"
  when: manual
  # rules:
  #   - if: $CI_COMMIT_MESSAGE =~ /^.*\[build all\].*$/s
  #   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  needs: ['is-it-pretty']
  stage: deploy
  before_script:
    - *install-pnpm
  script:
    - pnpm install
    - pnpm build
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
