image: docker.io/woss/gitpod-workspace:gitpod_workspace-full_2022-05-08-14-31-53

tasks:
  - name: install deps
    init: |
      pnpm config set store-dir ../.pnpm-store
      pnpm install
  - name: start dev
    command: pnpm dev

ports:
  - port: 7776
    visibility: public
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode-nightly
