image: node:18-bullseye

stages:
  - check
  - test
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules
    - ANAGOLAY_WEBSITE_CID
    - .pnpm-store

# include this where you need it. like in before_script
.install-ipfs-and-setup: &install-ipfs-and-setup
  - echo "Downloading anagolay ipfs CLI which works with the ipfsAuthProxy."
  - curl https://ipfs.anagolay.network/ipfs/bafybeigiuuavnlqy7czvxlvxdrqzcsvm7ezfkbbq4jwksl77lk5f7tlhia > /usr/local/bin/ipfsCli
  - chmod +x /usr/local/bin/ipfsCli

# https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#yaml-anchors-for-scripts
.install-pnpm: &install-pnpm
  - curl https://ipfs.anagolay.network/ipfs/Qma47CC3qBnMbBNsMQrn5viN7XGw4tp58fQWVTEiF2PEy8 > /usr/local/bin/pnpm
  - chmod +x /usr/local/bin/pnpm
  - pnpm config set store-dir .pnpm-store
  - node --version
  - pnpm --version
  - git --version

is-it-pretty:
  stage: check
  before_script:
    - *install-pnpm
  script:
    - pnpm install
    - pnpm lint

build-code:
  stage: test
  needs: ['is-it-pretty']
  before_script:
    - *install-pnpm
  script:
    - pnpm install
    - pnpm build

upload-to-ipfs:
  needs: ['is-it-pretty']
  stage: deploy
  before_script:
    - *install-ipfs-and-setup
    - *install-pnpm
  script:
    - set -e

    - echo 'Building ...'
    - pnpm build

    - echo "Uploading to IPFS ..."
    - IPFS_PIN=false ipfsCli add --onlyCid build > ANAGOLAY_WEBSITE_CID
    - echo "The Website is published with the CID:" && cat ANAGOLAY_WEBSITE_CID
    - echo "https://$(cat ANAGOLAY_WEBSITE_CID).ipfs.anagolay.network/"
  # when: manual
  # rules:
  #   - if: $CI_COMMIT_MESSAGE =~ /^.*\[build all\].*$/s
  #   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  needs: ['is-it-pretty']
  stage: deploy
  before_script:
    - *install-pnpm
  script:
    - pnpm install
    - pnpm build
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
