image: node:16-bullseye
pages:
  stage: deploy
  script:
    - curl https://ipfs.anagolay.network/ipfs/QmeCUX9cK4YKdTbNVq3jg5cJPvz8uQiQmb4AKKd7niy4kY > /usr/local/bin/pnpm
      - chmod +x /usr/local/bin/pnpm
      - pnpm i
      - pnpm build
      - mv build public
  artifacts:
    paths:
      - public
